set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_VERSION 19)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

find_program(ZIG_EXECUTABLE zig REQUIRED)

set(ZIG_WRAPPER_DIR "${CMAKE_BINARY_DIR}/zig-wrappers")
file(MAKE_DIRECTORY "${ZIG_WRAPPER_DIR}")

set(ZIG_CC_WRAPPER "${ZIG_WRAPPER_DIR}/zig-cc")
set(ZIG_CXX_WRAPPER "${ZIG_WRAPPER_DIR}/zig-cxx")

file(WRITE "${ZIG_CC_WRAPPER}" "#!/bin/bash\nexec ${ZIG_EXECUTABLE} cc -target x86_64-macos \"$@\"\n")
file(WRITE "${ZIG_CXX_WRAPPER}" "#!/bin/bash\nexec ${ZIG_EXECUTABLE} c++ -target x86_64-macos \"$@\"\n")

execute_process(COMMAND chmod +x "${ZIG_CC_WRAPPER}")
execute_process(COMMAND chmod +x "${ZIG_CXX_WRAPPER}")

set(CMAKE_C_COMPILER "${ZIG_CC_WRAPPER}")
set(CMAKE_CXX_COMPILER "${ZIG_CXX_WRAPPER}")

set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)

set(CMAKE_OSX_DEPLOYMENT_TARGET "10.9")

set(CMAKE_C_FLAGS_INIT "-mmacosx-version-min=10.9")
set(CMAKE_CXX_FLAGS_INIT "-mmacosx-version-min=10.9")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_SHARED_LIBRARY_SUFFIX ".dylib")
set(CMAKE_SHARED_MODULE_SUFFIX ".dylib")

set(CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS "-shared")
set(CMAKE_SHARED_LIBRARY_CREATE_CXX_FLAGS "-shared")

set(CMAKE_SHARED_LIBRARY_PREFIX "lib")

set(CMAKE_MACOSX_RPATH ON)